#### General information about the project    ####
#### All this will be visible on DataCamp.com ####
title          : "Reducing Traffic Mortality in the USA"
description    : >
  How can we find a good strategy for reducing traffic-related deaths?
long_description: |

While the rate of fatal road accidents rate have been decreasing steadily since
the 80's, the past 10 years have seen a stagnation in this reduction. Coupled
with the increase number of miles driven in the nation, the total number of
traﬃc related fatalities has now reached a 10 year high and is rapidly
increasing. By looking at the demographics of traﬃc accident victims for each
US state, we find that there is a lot of variation between states. Now we want
to understand if there are patterns in this variation in order to derive
suggestions for a policy action plan. In particular, instead of implementing a
costly nation-wide plan we want to focus on groups of states with similar
profiles. How can we find such groups in a statistically sound way and
communicate the result effectively?

This Project lets you practice the skills from [Introduction to shell for data
science](https://www.datacamp.com/courses/introduction-to-shell-for-data-science)
including how to navigate the file system and view files; [pandas
Foundations](https://www.datacamp.com/courses/pandas-foundations) including
reading, exploring, filtering, and grouping data; [Manipulating data frames
with
pandas](https://www.datacamp.com/courses/manipulating-dataframes-with-pandas)
including how to reshape data into the long format and how to perform multiple
aggregations; [Merging data frames with
pandas](https://www.datacamp.com/courses/merging-dataframes-with-pandas)
including how two merge two dataframes; [Unsupervised Learning in
Python](https://www.datacamp.com/courses/unsupervised-learning-in-python)
including KMeans clustering, dimensionally reduction through PCA, and
visualizations using `matplotlib`; [Supervised Learning with
scikit-learn](https://www.datacamp.com/courses/supervised-learning-with-scikit-learn)
including multivariate regression; [Intermediate Python for Data
Science](https://www.datacamp.com/courses/intermediate-python-for-data-science)
including visualizations using `matplotlib`; and [Data Visuazliation in
seaborn](https://www.datacamp.com/courses/data-visualization-with-seaborn)
inclusing statistical visualizations using `seaborn`. We recommend that you
review the appropriate sections of those courses before starting this Project.

time_needed: "60 minutes" # "30/45/60 minutes".

#### Metadata regarding course requirements and topics ####
#### This will be updated by your DataCamp contact     ####
technology: 2 # 1 == R, 2 == python, 3 == sql
# IDs for courses that are prerequisites
# See https://mb.datacamp.com/question/126 for IDs
prerequisites:
  - 799
difficulty_level: 2 # 1 == easy, 2 == medium, 3 == hard
# IDs for the topics the project covers
# See https://authoring.datacamp.com/projects/projects-repo-structure.html#project-yml for IDs
topics:
  - 3
  - 4
  - 6
  - 8

#### Technical settings for the docker image running the project ####
#### This will be updated by your DataCamp contact.              ####
language       : python # One of r, python or sql
# The name of the docker image used to run the course
from           : 'python-notebooks-prod:v1.1.0'
runtime_config : default # default/heavy . Set to heavy for more resource intensive projects.
